import { ReelCategory, InteractionType, ReelInteraction } from '../types/reel';
import { RecommendationCategory } from '../types/analysis';

export const REEL_CATEGORIES: ReelCategory[] = [
  'Coding',
  'Programming Meme',
  'Career',
  'AI',
  'Gadgets',
  'Tech News',
  'Gaming',
  'Entertainment',
  'Other',
];

export const INTERACTION_TYPES: InteractionType[] = [
  'Watched',
  'Liked',
  'Saved',
  'Shared',
];

export const RECOMMENDATION_CATEGORIES: RecommendationCategory[] = [
  'AI',
  'DSA',
  'Java',
  'HLD',
  'Cybersecurity',
  'Cloud',
  'Hardware',
  'Career',
  'Other',
];

export interface PresetScenario {
  id: string;
  name: string;
  badge: string;
  tagline: string;
  description: string;
  reels: ReelInteraction[];
}

export const PRESET_SCENARIOS: PresetScenario[] = [
  {
    id: 'official-trap',
    name: 'Official Judge Trap (SWE Inference)',
    badge: '🏆 Official Trap',
    tagline: 'Java Meme + SWE Lifestyle + Coding Joke + Laptop Comparison',
    description: 'Tests semantic cross-Reel reasoning. A shallow keyword system simply recommends generic Java. TechReel AI infers a broader Software Engineering interest and recommends High-Level System Design (HLD).',
    reels: [
      {
        id: 'trap-1',
        title: 'Java Runtime Exception Meme',
        caption: 'When your Java code compiles on the first try with 0 errors but throws NullPointerException at runtime 💀 #Java #NullPointer #CodeMeme',
        category: 'Programming Meme',
        interactionType: 'Liked',
        watchPercentage: 100,
        timestamp: Date.now() - 3600000 * 4,
        url: 'https://youtube.com/shorts/sample-java-meme',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        creatorName: 'DevHumor & Code',
        creatorAvatar: '☕',
        creatorNotes: 'Focused on JVM runtime behavior and defensive null-checking techniques.',
        tags: ['Java', 'NullPointerException', 'JVM', 'Runtime', 'BackendDebugging'],
        comments: [
          {
            id: 'c1-1',
            authorName: 'Alex_Dev',
            authorRole: 'Backend Engineer',
            content: 'Optional.ofNullable() saved my life from this exact runtime nightmare!',
            timestamp: Date.now() - 3600000 * 3,
            likes: 42,
            isLiked: true,
          },
          {
            id: 'c1-2',
            authorName: 'CodeCraft',
            authorRole: 'Tech Lead',
            content: 'Wait until you discover Kotlin null safety, you will never write raw Java again 🚀',
            timestamp: Date.now() - 3600000 * 2,
            likes: 28,
          },
          {
            id: 'c1-3',
            authorName: 'TechReel AI Assistant',
            authorRole: 'AI Agent Insight',
            content: '💡 Inferred signal: Student understands compile-time vs runtime execution differences.',
            timestamp: Date.now() - 3600000 * 1,
            likes: 19,
            isAiInsight: true,
          },
        ],
        aiFeedback: {
          hookScore: 94,
          hookEvaluation: 'Immediate visual humor grabs developer attention in first 1.8 seconds.',
          pacingScore: 88,
          pacingEvaluation: 'Fast 15-second delivery keeps viewer retention at 100%.',
          techClarityScore: 92,
          techClarityEvaluation: 'Clear demonstration of NullPointerException without fluff.',
          viralityScore: 90,
          sentimentBreakdown: {
            positive: 85,
            neutral: 12,
            negative: 3,
            summary: 'High resonance among junior and intermediate software engineers.',
          },
          keyStrengths: [
            'Relatable debugging pain point with high shareability',
            'Strong visual meme hook',
            'Reinforces runtime vs compile-time mental model',
          ],
          improvements: [
            'Could briefly highlight `Objects.requireNonNull()` or `Optional` pattern in caption',
            'Add link to JVM memory model breakdown',
          ],
          inferredTopics: ['Java Runtime', 'Null Safety', 'Defensive Programming', 'Exception Handling'],
          actionableSummary: 'High-performing humorous tech reel that signals foundational language syntax understanding.',
        },
        transcript: [
          { timestamp: '00:00', seconds: 0, text: 'When your code compiles with 0 errors on first attempt...' },
          { timestamp: '00:05', seconds: 5, text: 'Pressing Run: Process finished with exit code 1 (NullPointerException).' },
          { timestamp: '00:10', seconds: 10, text: 'Debugging line 42: obj.getUser().getAddress().getCity();' },
        ],
      },
      {
        id: 'trap-2',
        title: 'Day in Life: Backend Software Engineer',
        caption: 'Morning standup, microservice code review, debugging a Redis cache stampede, and optimizing database indexes. #SWE #Backend #TechCareer',
        category: 'Career',
        interactionType: 'Watched',
        watchPercentage: 95,
        timestamp: Date.now() - 3600000 * 3,
        url: 'https://youtube.com/shorts/sample-swe-lifestyle',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        creatorName: 'Sarah In Tech',
        creatorAvatar: '👩‍💻',
        creatorNotes: 'Walkthrough of real production engineering responsibilities at scale.',
        tags: ['Backend', 'Redis', 'Microservices', 'DatabaseOptimization', 'Career'],
        comments: [
          {
            id: 'c2-1',
            authorName: 'Marcus_Cloud',
            authorRole: 'SRE',
            content: 'How did you handle the Redis cache stampede? Mutex lock or probabilistic early expiration?',
            timestamp: Date.now() - 3600000 * 2,
            likes: 31,
          },
          {
            id: 'c2-2',
            authorName: 'Priya_Tech',
            authorRole: 'CS Student',
            content: 'This inspired me to study database indexing and query execution plans!',
            timestamp: Date.now() - 3600000 * 1,
            likes: 18,
          },
        ],
        aiFeedback: {
          hookScore: 91,
          hookEvaluation: 'Realistic day-in-the-life structure sets authentic expectations.',
          pacingScore: 93,
          pacingEvaluation: 'Smooth progression from morning standup to deep architecture review.',
          techClarityScore: 89,
          techClarityEvaluation: 'Good high-level overview of distributed caching and DB optimization.',
          viralityScore: 94,
          sentimentBreakdown: {
            positive: 92,
            neutral: 7,
            negative: 1,
            summary: 'Extremely positive engagement from aspiring backend developers.',
          },
          keyStrengths: [
            'Demonstrates practical enterprise technology stacks',
            'Highlights distributed systems and caching concepts',
            'Bridges theoretical CS concepts to real-world career roles',
          ],
          improvements: [
            'Add 3-second animated diagram of Redis cache flow',
            'Include tech stack tags in video overlay',
          ],
          inferredTopics: ['Distributed Systems', 'Redis Caching', 'Microservices', 'Software Engineering Career'],
          actionableSummary: 'High-value career video signalling strong interest in scalable backend architecture.',
        },
        transcript: [
          { timestamp: '00:00', seconds: 0, text: '9:00 AM: Standup with distributed team & Sprint review.' },
          { timestamp: '00:06', seconds: 6, text: '11:00 AM: Investigating p99 latency spike in Redis cluster.' },
          { timestamp: '00:12', seconds: 12, text: '2:00 PM: Adding composite index to Postgres table to drop query time from 400ms to 8ms.' },
        ],
      },
      {
        id: 'trap-3',
        title: 'Whiteboard Coding Interview Struggle',
        caption: 'Interviewer: "Now invert a binary tree and handle all edge cases in O(1) space." Me: 👁️👄👁️ #LeetCode #DSA #Interview',
        category: 'Coding',
        interactionType: 'Saved',
        watchPercentage: 90,
        timestamp: Date.now() - 3600000 * 2,
        url: 'https://youtube.com/shorts/sample-coding-interview',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        creatorName: 'AlgorithmicMind',
        creatorAvatar: '🌳',
        creatorNotes: 'Satirical look at whiteboard interview pressure with algorithmic takeaways.',
        tags: ['DSA', 'LeetCode', 'BinaryTree', 'Algorithms', 'TechInterview'],
        comments: [
          {
            id: 'c3-1',
            authorName: 'Karan_K',
            authorRole: 'FAANG Candidate',
            content: 'Morris Traversal is the trick for O(1) space binary tree traversal!',
            timestamp: Date.now() - 3600000 * 2,
            likes: 54,
            isLiked: true,
          },
          {
            id: 'c3-2',
            authorName: 'TechReel AI Assistant',
            authorRole: 'AI Agent Insight',
            content: '💡 Inferred signal: Active interview preparation & Data Structures & Algorithms focus.',
            timestamp: Date.now() - 3600000 * 1,
            likes: 15,
            isAiInsight: true,
          },
        ],
        aiFeedback: {
          hookScore: 96,
          hookEvaluation: 'Instant relatable LeetCode scenario with viral comedic audio.',
          pacingScore: 90,
          pacingEvaluation: 'Crisp 12-second punchline.',
          techClarityScore: 86,
          techClarityEvaluation: 'Clear algorithmic topic with immediate interview context.',
          viralityScore: 95,
          sentimentBreakdown: {
            positive: 89,
            neutral: 9,
            negative: 2,
            summary: 'High viral engagement among CS students preparing for campus placements.',
          },
          keyStrengths: [
            'Hyper-relevant interview topic (Binary Tree inversion)',
            'Strong community discussion in comments on algorithmic optimizations',
            'Clear indicator of DSA & competitive programming interest',
          ],
          improvements: [
            'Overlay Morris Traversal code snippet at the end for educational value',
          ],
          inferredTopics: ['Data Structures', 'Tree Algorithms', 'Interview Preparation', 'Time & Space Complexity'],
          actionableSummary: 'High-engagement coding reel indicating algorithmic readiness and placement focus.',
        },
        transcript: [
          { timestamp: '00:00', seconds: 0, text: 'Interviewer: Can you invert a binary tree recursively?' },
          { timestamp: '00:04', seconds: 4, text: 'Me: Easy, swap left and right pointers in O(N).' },
          { timestamp: '00:08', seconds: 8, text: 'Interviewer: Great, now do it iteratively in O(1) auxiliary space.' },
        ],
      },
      {
        id: 'trap-4',
        title: 'M3 Max vs ThinkPad for Docker & Local Dev',
        caption: 'Comparing compile speeds, thermals, and Docker container performance on 16-core Apple Silicon vs Intel Core i9. #Laptops #DevSetup #Hardware',
        category: 'Gadgets',
        interactionType: 'Shared',
        watchPercentage: 85,
        timestamp: Date.now() - 3600000 * 1,
        url: 'https://youtube.com/shorts/sample-laptop-comparison',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
        creatorName: 'HardwareBenchmarks',
        creatorAvatar: '💻',
        creatorNotes: 'Benchmarking containerized microservices and multi-threaded C++ compilation.',
        tags: ['Hardware', 'Docker', 'M3Max', 'AppleSilicon', 'DevEnvironment'],
        comments: [
          {
            id: 'c4-1',
            authorName: 'David_S',
            authorRole: 'DevOps Lead',
            content: 'Unified memory bandwidth on Apple Silicon makes running 10 Docker containers simultaneous a breeze.',
            timestamp: Date.now() - 3600000 * 1,
            likes: 24,
          },
        ],
        aiFeedback: {
          hookScore: 89,
          hookEvaluation: 'Side-by-side thermal camera and compile timer provides immediate visual hook.',
          pacingScore: 88,
          pacingEvaluation: 'Clear benchmarks presented without dragging.',
          techClarityScore: 94,
          techClarityEvaluation: 'Precise metrics: build times in seconds, memory bandwidth, thermals.',
          viralityScore: 91,
          sentimentBreakdown: {
            positive: 88,
            neutral: 10,
            negative: 2,
            summary: 'High interest from engineers evaluating workstation hardware upgrades.',
          },
          keyStrengths: [
            'Empirical benchmark data for developer workloads',
            'Clear relevance to Docker and local development tooling',
            'Strong cross-signal indicating serious software development practice',
          ],
          improvements: [
            'Add breakdown of power efficiency per Watt',
          ],
          inferredTopics: ['Developer Hardware', 'Docker Containerization', 'Compilation Performance', 'System Architecture'],
          actionableSummary: 'High-signal hardware reel demonstrating practical developer environment needs.',
        },
        transcript: [
          { timestamp: '00:00', seconds: 0, text: 'Benchmarking a 50,000-line Rust codebase on M3 Max vs Core i9.' },
          { timestamp: '00:05', seconds: 5, text: 'M3 Max finishes compilation in 14.2 seconds on battery.' },
          { timestamp: '00:10', seconds: 10, text: 'Spinning up 8 containerized microservices with Docker Compose.' },
        ],
      },
    ],
  },
  {
    id: 'ai-research',
    name: 'AI & Deep Learning Enthusiast',
    badge: '🧠 AI / ML Track',
    tagline: 'PyTorch + LLM Fine-Tuning + Transformer Architecture',
    description: 'Demonstrates deep context matching for AI engineering, inferring interest in scalable LLM deployment and quantization.',
    reels: [
      {
        id: 'ai-1',
        title: 'PyTorch vs JAX: Tensor Ops Benchmark',
        caption: 'Comparing GPU memory utilization and automatic differentiation benchmarks between PyTorch 2.0 and JAX. #PyTorch #JAX #DeepLearning',
        category: 'AI',
        interactionType: 'Saved',
        watchPercentage: 100,
        timestamp: Date.now() - 3600000 * 4,
      },
      {
        id: 'ai-2',
        title: 'How Transformer Self-Attention Actually Computes',
        caption: '3D animation visualizing Query, Key, Value matrix multiplication and attention weights in LLMs. #Transformer #NLP #AI',
        category: 'AI',
        interactionType: 'Liked',
        watchPercentage: 95,
        timestamp: Date.now() - 3600000 * 3,
      },
      {
        id: 'ai-3',
        title: 'Fine-Tuning LLaMA-3 with LoRA and QLoRA',
        caption: 'Low-rank adaptation explained in 60 seconds with practical VRAM consumption breakdown. #LLM #OpenSourceAI #LoRA',
        category: 'AI',
        interactionType: 'Saved',
        watchPercentage: 90,
        timestamp: Date.now() - 3600000 * 2,
      },
      {
        id: 'ai-4',
        title: 'NVIDIA H100 vs B200 Tensor Core Architecture',
        caption: 'FP4 precision computing, NVLink 5 bandwidth, and inference throughput for frontier models. #Hardware #NVIDIA #TechNews',
        category: 'Gadgets',
        interactionType: 'Shared',
        watchPercentage: 88,
        timestamp: Date.now() - 3600000 * 1,
      },
    ],
  },
  {
    id: 'hardware-gaming',
    name: 'GPU Architecture & Systems Hardware',
    badge: '⚡ Hardware / Systems',
    tagline: 'Custom PC Build + Unreal Engine Nanite + Linux Kernel',
    description: 'Infers interest in Computer Graphics, GPU compute pipelines, and Low-Level Systems Programming.',
    reels: [
      {
        id: 'hw-1',
        title: 'Custom Hardline Water-Cooled Rig Build',
        caption: 'Bending acrylic tubes and optimizing custom dual-radiator loop pressure for 600W thermal dissipation. #PCBuild #CustomWatercooling #Hardware',
        category: 'Gadgets',
        interactionType: 'Liked',
        watchPercentage: 95,
        timestamp: Date.now() - 3600000 * 4,
      },
      {
        id: 'hw-2',
        title: 'RTX 4090 vs RX 7900 XTX Ray Tracing Stress Test',
        caption: 'Path-tracing frame rate comparison in Cyberpunk 2077 with DLSS 3.5 Ray Reconstruction enabled. #Gaming #GPU #RayTracing',
        category: 'Gaming',
        interactionType: 'Watched',
        watchPercentage: 85,
        timestamp: Date.now() - 3600000 * 3,
      },
      {
        id: 'hw-3',
        title: 'How Unreal Engine 5 Nanite Renders Billions of Polygons',
        caption: 'Meshlet clustering, GPU-driven occlusion culling, and hardware rasterization pipeline explained. #GameDev #UnrealEngine #Graphics',
        category: 'Tech News',
        interactionType: 'Saved',
        watchPercentage: 92,
        timestamp: Date.now() - 3600000 * 2,
      },
      {
        id: 'hw-4',
        title: 'Why Steam Deck Runs Games Smoothly on Linux (Proton/Vulkan)',
        caption: 'Translating DirectX 12 calls to Vulkan via DXVK with zero shader stutter. #Linux #Vulkan #SteamDeck',
        category: 'Gaming',
        interactionType: 'Shared',
        watchPercentage: 90,
        timestamp: Date.now() - 3600000 * 1,
      },
    ],
  },
  {
    id: 'mixed-entertainment',
    name: 'Mixed Entertainment (Weak Signal Test)',
    badge: '⚠️ Mixed Signal Test',
    tagline: 'Comedy + Cooking + Cat Video + Single CSS Reel',
    description: 'Tests the AI Mixed Signal Detector: when inputs are conflicting and lack a dominant technical direction, it avoids forcing a fake technology recommendation.',
    reels: [
      {
        id: 'mix-1',
        title: 'Stand-up comedy about everyday traffic',
        caption: 'Why driving 2 miles takes 45 minutes in rush hour 😂 #Comedy #StandUp #Relatable',
        category: 'Entertainment',
        interactionType: 'Liked',
        watchPercentage: 90,
        timestamp: Date.now() - 3600000 * 4,
      },
      {
        id: 'mix-2',
        title: 'Street food stall making giant ramen bowls',
        caption: 'Handmade noodles in Tokyo with 24-hour pork broth. #Foodie #Ramen #TokyoEats',
        category: 'Entertainment',
        interactionType: 'Watched',
        watchPercentage: 85,
        timestamp: Date.now() - 3600000 * 3,
      },
      {
        id: 'mix-3',
        title: 'Cat knocking cups off table in slow motion',
        caption: 'He looked me in the eye before pushing it over 🐱 #CatMemes #Pets #Funny',
        category: 'Entertainment',
        interactionType: 'Watched',
        watchPercentage: 70,
        timestamp: Date.now() - 3600000 * 2,
      },
      {
        id: 'mix-4',
        title: 'Cool 3D button hover animation in CSS',
        caption: 'Pure CSS transform-style preserve-3d button effect. #CSS #WebDev #FrontEnd',
        category: 'Coding',
        interactionType: 'Liked',
        watchPercentage: 40,
        timestamp: Date.now() - 3600000 * 1,
      },
    ],
  },
];
